### ISSUE TITLE
Add roles to allow partner agencies to view boarding reports

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-realm#133]
Add a new role to the rules for `Photo` and `BoardingReports` to check if the user's agency is in the `partnerAgencies` array for the agency that owns the current document.

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Realm rules to allow partner agencies to view reports](https://trello.com/c/ZgjpKQ9n/317-add-realm-rules-to-allow-partner-agencies-to-view-reports)
