### ISSUE TITLE
Add roles to allow agency admins and officers to view `Agency` documents

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-realm#134]
All users should be able to view all agencies.

An agency admin should be able to edit documents for their agency.

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add roles to allow officers and agency admins to access `Agency` collection](https://trello.com/c/1utYOs20/318-add-roles-to-allow-officers-and-agency-admins-to-access-agency-collection)
