### ISSUE TITLE
Add `description` fields for Activity, Fishery, Gear, or Catch

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-realm#135]
This is required for https://github.com/WildAid/o-fish-ios/issues/285

**Comment by Sheeri** [comment]
FWIW - if possible - the ideal is to have the "other" value just save in the field, as if it was a menu item. so, if menu item is 'Other' (or a translation thereof) then save the 'Description' field to the actual field (e.g. Activity=Other, description='Sailing', save 'Sailing' to Activity in the database).

**Comment by Sheeri** [comment]
This can be done in the ViewModel, no need for a separate field.
