### ISSUE TITLE
Create guest developer user & agency for Hacktoberfest

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-realm#136]
This functionality is to support users creating their own agency-admin user in a shared instance of the O-FISH Realm app.

There is a matching web issue for this feature: https://github.com/WildAid/o-fish-web/issues/197

- [x] Update README to indicate that anonymous authentication must be enabled if you want to host O-FISH in this development model

### Create new function `regNewAgency`:

- [x] If there is already an `Agency` document with the same name, return with an error that the "Agency already exists"
- [x] Insert new document into the `Agency` collection
- [x] If there is already a `User` document with the same email address, return with an error that the "User already exists"
- [x] Insert new document into the `User` collection
- [x] Return success/error depending on the results

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create issues for Hacktoberfest guest agency creation](https://trello.com/c/lzDYKBjq/320-create-issues-for-hacktoberfest-guest-agency-creation)

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement developer agencies for Hacktoberfest - Realm](https://trello.com/c/KsNQhZe9/323-implement-developer-agencies-for-hacktoberfest-realm)
