### ISSUE TITLE
Failed: wildaid.DutyChange: error creating collection wildaid.DutyChange

### ISSUE THREAD

**Issue by RitikPandey1** [WildAid/o-fish-realm#141]
![err](https://user-images.githubusercontent.com/57366926/94254252-26adba00-ff44-11ea-84f7-508ac9dd5fa7.PNG)

I am follow all the steps mentioned in doc : https://wildaid.github.io/foundation/2020/06/09/Data-Import.html , but still getting this error while importing data , please help. 
 @dcoupal @Sheeri @10genjen @Azzoo @am-MongoDB

**Comment by am-MongoDB** [comment]
@RitikPandey1 I've not been able to reproduce this – what version of `mongorestore` are you using (`mongorestore --version`)?

**Comment by RitikPandey1** [comment]
@am-MongoDB  mongorestore version: 100.1.1

**Comment by am-MongoDB** [comment]
Same here.

What version is your Atlas cluster?

**Comment by RitikPandey1** [comment]
cluster version 4.2.9

**Comment by am-MongoDB** [comment]
I was just able to reproduce it on 4.2. You need to upgrade to 4.4, as that's where the collections were dumped from

**Comment by RitikPandey1** [comment]
@am-MongoDB  Thank you , it worked on 4.4.
