### ISSUE TITLE
Add developerMode value

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-realm#145]
The functionality to allow anonymous users to register new developer users in a sandbox environment should be gated on a new `developerMode` Realm value.

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add "Developer Mode" value and use that as a flag in "risky" functions such as `regNewAgency`](https://trello.com/c/mrE1d17C/356-add-developer-mode-value-and-use-that-as-a-flag-in-risky-functions-such-as-regnewagency)
