### ISSUE TITLE
strategy=replace complains of duplicates

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-realm#147]
A community member was trying to do a realm import with the command: 
ealm-cli import --strategy=replace --include-dependencies --app-id=the_app_id 
and got: 
failed to diff app with currently deployed instance: error: must specify unique names when importing MongoDB Rules; duplicate name: wildaid.MenuData

Let's investigate whether or not this is expected and if there's a different way we should export the realm template for importing.

This is important for being able to update exisiting Realm code.

**Comment by Sheeri** [comment]
The import of realm functions has been much improved in current versions.
