### ISSUE TITLE
Could not import with AWS credentials

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-realm#148]
Sheeri kept getting the following when trying to import to a new instance with:
realm-cli import --strategy=replace --include-dependencies --app-id=the_app_id
And got the error:
realm-cli failed to diff app with currently deployed instance: error: validating Service: 'AWS: could not find secret' (and then the secret).  

A note: 
realm-cli secrets add --name=AWS-secret-key --value=my-aws-secret-api-key --app-id=REALM_APP_ID 
was successful - and was tried with both the AWS access key ID and the AWS secret access key

aws configure list showed the active region, and last chars of the api key and secret, that matched what was being used.

IAM roles showed that the key was active; a new key/secret pair was made and tried, with the same error.

The values in the following files were set:  values/awsRegion.json services/AWS/config.json

**Comment by Sheeri** [comment]
This was fixed in a later version.
