### ISSUE TITLE
Bootstrap new development agencies with menu and report data

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-realm#159]
**Is your feature request related to a problem? Please describe.**
When running and sandboxing mode, it's a pain to have to go into the Web UI and create menu items for my new agency before being able to create reports in the mobile app.

**Describe the solution you'd like**
Nominate one agency as the template-agency (e.g. WildAid) through a new Realm Value and then a trigger should copy any reports and menu data from the template agency to the new agency.

The trigger should be deactivated by default.

The trigger should do nothing unless `developerMode` is set to `true`.

**Additional context**
This is only intended to be used in developer / sandbox, mode where an anonymous user is able to create a new user and agency.

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Re: Automatic agency data for sandbox](https://trello.com/c/1Nz22sZy/392-re-automatic-agency-data-for-sandbox)
