### ISSUE TITLE
Enhanced data sharing between partner agencies

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-realm#163]
**Is your feature request related to a problem? Please describe.**
Need new data/roles/rules to allow partner agencies to read reports from the donor agency.

**Describe the solution you'd like**
- [x] Don’t change the contents or meaning of partnerAgencies – though we should rename it to make it clear that it refers to what this agency is allowing other agencies to access - `outboundPartnerAgencies`
- [x] Add a new array to the `Agency` document – `inboundPartnerAgencies` - where each element contains: a `Bool` named `triaged` (defaults to `false`) to indicated whether the agency-admin has reviewed whether to grant access to the donor agency’s reports to the rest of their own agency; a `Bool` named `agencyWideAccess` (defaults to `false`) to indicate whether all agency members can read the donor agency’s reports; a `String` named `name` which is the name of the donor agency
- [x] Add an array called `inboundPartnerAgencies` to the `User` document (that can only be written to by the agency admin, or a global admin) which is an array of `String`, where each element is the name of an agency that the user has read-access to. This is written to by the agency/global admin; a regular user can read but not write to it.
- [x] A trigger will add or remove an agency's name to other `Agency` `inboundPartnerAgencies` arrays when an `Agency` document is inserted, updated, replaced, ~~or deleted~~
- [x] All users in an agency can read that agency's `inboundPartnerAgencies` data
- [x] A user of agency `myAgency` can read (but not write) another agency's reports if the donor agency has `myAgency` in their `outboundPartnerAgencies` array and the current date is in bounds *and* either their own agency has `inboundPartnerAgencies[donorAgency].agencyWideAccess` set to true *or* their `User` document includes `donorAgency` in `inboundPartnerAgencies`

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [O-FISH – design new Realm roles/rules to implement new data-sharing scheme](https://trello.com/c/f19ICTNa/407-o-fish-design-new-realm-roles-rules-to-implement-new-data-sharing-scheme)

**Comment by am-MongoDB** [comment]
The schema changes will be implemented in advance under https://github.com/WildAid/o-fish-realm/issues/164

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WildAid - Realm rules for agency sharing](https://trello.com/c/uuPLf9Wu/409-wildaid-realm-rules-for-agency-sharing)
