### ISSUE TITLE
Just the schema changes for enhanced agency data sharing

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-realm#164]
**Is your feature request related to a problem? Please describe.**
Need to get (jus) the schema changes from https://github.com/WildAid/o-fish-realm/issues/163 implemented ASAP so that the web work can be completed.

**Describe the solution you'd like**
Implement the schema changes described in https://github.com/WildAid/o-fish-realm/issues/163

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [O-FISH schema changes for enhanced agency sharing](https://trello.com/c/7Hl1FIV8/408-o-fish-schema-changes-for-enhanced-agency-sharing)
