### ISSUE TITLE
Checking for partners has a couple of bugs

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-realm#179]
**Describe the bug**
Once the web app was able to exercise the new agency partnership functionality, a couple of discrepancies were found between the web app, `Agency` schema, and `isPartner` Function

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS X]
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Troubleshoot EPAM issues](https://trello.com/c/h3PkP4OB/441-troubleshoot-epam-issues)
