### ISSUE TITLE
Agencies page and Officers

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-realm#189]
On the Agencies page (/#/agencies - only available to global and agency admins) the agency officers are shown. However the actual names shown are Captains from boarding records - they should be records from the User collection that match on agency.name.

![Screen Shot 2020-10-12 at 10 48 58 AM](https://user-images.githubusercontent.com/1767528/95761235-0424dc00-0c7a-11eb-8e62-b00bcdabed7f.png)

("Jack Harknass" is a captain. Every agency has at least one user, so the agencies that show "N/A" are also incorrect).

**Comment by Dusch4593** [comment]
Sure thing! Per the official contribution guidelines, is this the link I need to go to? 

https://github.com/Dusch4593/o-fish-realm/pull/new/fix_issue_189

**Comment by Dusch4593** [comment]
I pushed the changes you suggested to the `source.js` file and created a [pull request](https://github.com/WildAid/o-fish-realm/pull/190). There are no conflicts with the base branch but it failed the checks. Git/ GitHub workflows are still sort of new to me, but what does it mean when your PR fails all the checks?

**Comment by Sheeri** [comment]
Hi @Dusch4593 that particular check was to see if this was your first PR on the repo, and if so, say thanks for making your first submission. So in this case, it's not concerning that it failed.
